/**
 * Code-change pipeline for Mimir.
 *
 * Adam talks to Mimir → Mimir calls propose_code_change(repo, instruction)
 *   → A small agentic sub-loop reads files, stages edits, calls done()
 *   → We atomically commit all staged edits to a new branch
 *   → Open a PR
 *   → Return PR URL + branch + diff summary + (later) Vercel preview URL
 * Adam reviews → says "ship it" → Mimir calls merge_pull_request
 *   → squash-merge, Vercel auto-deploys main
 *
 * Safety:
 *   - Repo allowlist enforced by github-client.ts
 *   - File path blocklist (no .env, no lock files, no secrets)
 *   - Max files edited per PR: 5
 *   - Max sub-loop iterations: 15
 *   - Max bytes per file: 200KB (we ignore huge files)
 *   - Squash-merge only, never force-push
 */
import Anthropic from '@anthropic-ai/sdk'
import {
  type RepoKey,
  MANAGED_REPOS,
  isManagedRepo,
  listRepoTree,
  readFile,
  createBranch,
  commitMultipleFiles,
  createPullRequest,
  getPullRequest,
  listOpenPullRequests,
  mergePullRequest,
  getVercelPreviewUrl,
  whoAmI,
  type PullRequest,
  type FileChange,
} from './github-client'

// =====================================================================
// CONSTANTS
// =====================================================================

const MODEL = 'claude-sonnet-4-6'
const MAX_ITERATIONS = 15
const MAX_FILES_EDITED = 5
const MAX_FILES_READ = 20
const MAX_FILE_BYTES = 200_000

const FORBIDDEN_PATH_PATTERNS: RegExp[] = [
  /^\.env(\..+)?$/,           // .env, .env.local, etc — secrets
  /\/\.env(\..+)?$/,
  /package-lock\.json$/,       // lock files: regenerated by package managers
  /pnpm-lock\.yaml$/,
  /yarn\.lock$/,
  /^node_modules\//,
  /^\.next\//,
  /^\.nuxt\//,
  /^\.vercel\//,
  /^dist\//,
  /^build\//,
  /\.(jpg|jpeg|png|gif|webp|mp4|mov|webm|pdf|woff2?|ttf|otf|eot)$/i, // binaries
]

function isForbiddenPath(path: string): { allowed: boolean; reason?: string } {
  for (const pattern of FORBIDDEN_PATH_PATTERNS) {
    if (pattern.test(path)) {
      return { allowed: false, reason: `path matches blocklist pattern ${pattern}` }
    }
  }
  if (path.startsWith('/') || path.includes('..')) {
    return { allowed: false, reason: 'absolute or traversal paths not allowed' }
  }
  return { allowed: true }
}

// =====================================================================
// SUB-AGENT TOOLS — what the inner Claude can call
// =====================================================================

const SUB_AGENT_TOOLS: Anthropic.Tool[] = [
  {
    name: 'list_repo_directory',
    description: 'List files in the repo (recursive). Call once at the start to orient yourself. Returns up to ~500 paths.',
    input_schema: {
      type: 'object',
      properties: {
        path_prefix: { type: 'string', description: 'Optional path prefix filter, e.g. "server/utils/" or "pages/". Leave empty to list everything.' },
      },
      required: [],
    },
  },
  {
    name: 'read_repo_file',
    description: "Read a file's full contents. Call this for every file you intend to edit BEFORE proposing an edit, so you know the exact text. Max 200KB. Max 20 reads per change.",
    input_schema: {
      type: 'object',
      properties: {
        path: { type: 'string' },
      },
      required: ['path'],
    },
  },
  {
    name: 'propose_edit',
    description: 'Stage a search/replace edit on a file you have already read. The edit applies at PR commit time. old_string must match exactly (including indentation) and appear once in the file. To make multiple edits in one file, call propose_edit multiple times.',
    input_schema: {
      type: 'object',
      properties: {
        path: { type: 'string' },
        old_string: { type: 'string' },
        new_string: { type: 'string' },
        reason: { type: 'string', description: 'One-sentence reason for this edit, for the PR body.' },
      },
      required: ['path', 'old_string', 'new_string', 'reason'],
    },
  },
  {
    name: 'propose_new_file',
    description: 'Stage creation of a brand new file. Use only when the change requires a file that does not exist yet.',
    input_schema: {
      type: 'object',
      properties: {
        path: { type: 'string' },
        content: { type: 'string' },
        reason: { type: 'string' },
      },
      required: ['path', 'content', 'reason'],
    },
  },
  {
    name: 'done',
    description: 'Call when all edits are staged. Provide a 1-3 sentence summary of what changed and why, in plain prose, for the PR body.',
    input_schema: {
      type: 'object',
      properties: {
        summary: { type: 'string' },
      },
      required: ['summary'],
    },
  },
]

const SUB_AGENT_SYSTEM_PROMPT = `You are a careful code-change engineer working inside Mimir, the operational lens of The Nordic Nerd.

You make a SMALL, FOCUSED edit to a single repo based on a one-line instruction from Adam. You are not architecting — you are surgically applying a change.

WORKFLOW
1. Call list_repo_directory ONCE at the start (with a path_prefix if the instruction tells you where to look).
2. Call read_repo_file on the 1-5 files relevant to the change. Read the WHOLE file before proposing edits to it.
3. Call propose_edit (or propose_new_file) to stage each change. old_string must match the file EXACTLY — same indentation, same line endings.
4. Call done(summary) when finished.

HARD RULES
- Maximum 5 files edited per change. If you'd need more, call done() with a summary explaining the split is too big and recommend the change be broken up.
- Never edit .env files, lock files, or binaries.
- Never edit a file you haven't read.
- Never invent imports, APIs, or package functions. If you're not sure something exists, search for it via read_repo_file on adjacent files.
- Match the existing code style — TypeScript strict, no \`any\`, no JS files, peer-to-peer voice in any user-facing copy.
- Read the repo's CLAUDE.md if it exists. Honor its rules.
- If the instruction is ambiguous, make the smallest reasonable interpretation and note the assumption in your done() summary.
- If the instruction is impossible or unsafe, call done() with an explanation of why you can't make the change — do not stage edits.

VOICE for the done() summary
Dry. Short. Match Mimir's voice. "Changed the queue widget's padding from 12px to 16px. One file: components/QueuePanel.vue." NOT "I have successfully implemented..."`

// =====================================================================
// STAGED EDIT TRACKING — per propose_code_change run
// =====================================================================

interface StagedEdit {
  path: string
  type: 'edit' | 'new'
  reason: string
  // For edits: search/replace pair. For new: content as new_content.
  old_string?: string
  new_string?: string
  new_content?: string
}

class EditStager {
  private edits: StagedEdit[] = []
  private fileContents: Map<string, string> = new Map() // path → current content (with staged edits applied)
  private readPaths: Set<string> = new Set()

  recordRead(path: string, content: string): void {
    this.readPaths.add(path)
    if (!this.fileContents.has(path)) this.fileContents.set(path, content)
  }

  hasRead(path: string): boolean {
    return this.readPaths.has(path)
  }

  readCount(): number {
    return this.readPaths.size
  }

  editedFiles(): string[] {
    return [...new Set(this.edits.map(e => e.path))]
  }

  stageEdit(path: string, oldString: string, newString: string, reason: string): { ok: boolean; error?: string } {
    const current = this.fileContents.get(path)
    if (current === undefined) return { ok: false, error: `file ${path} has not been read — call read_repo_file first` }
    const occurrences = current.split(oldString).length - 1
    if (occurrences === 0) return { ok: false, error: `old_string not found in ${path}. Re-read the file and use exact text.` }
    if (occurrences > 1) return { ok: false, error: `old_string appears ${occurrences} times in ${path}. Provide more surrounding context to make it unique.` }
    const updated = current.replace(oldString, newString)
    this.fileContents.set(path, updated)
    this.edits.push({ path, type: 'edit', reason, old_string: oldString, new_string: newString })
    if (this.editedFiles().length > MAX_FILES_EDITED) {
      // Roll back this edit
      this.fileContents.set(path, current)
      this.edits.pop()
      return { ok: false, error: `cannot edit more than ${MAX_FILES_EDITED} files in one change` }
    }
    return { ok: true }
  }

  stageNewFile(path: string, content: string, reason: string): { ok: boolean; error?: string } {
    if (this.fileContents.has(path)) {
      return { ok: false, error: `${path} already exists — use propose_edit instead` }
    }
    this.fileContents.set(path, content)
    this.edits.push({ path, type: 'new', reason, new_content: content })
    if (this.editedFiles().length > MAX_FILES_EDITED) {
      this.fileContents.delete(path)
      this.edits.pop()
      return { ok: false, error: `cannot touch more than ${MAX_FILES_EDITED} files in one change` }
    }
    return { ok: true }
  }

  /** Build the list of FileChanges to send to commitMultipleFiles */
  toChanges(): FileChange[] {
    return this.editedFiles().map((path) => ({
      path,
      content: this.fileContents.get(path) ?? null,
    }))
  }

  /** PR body — itemized reasons per edit */
  toPrBody(): string {
    const lines: string[] = []
    const byFile = new Map<string, StagedEdit[]>()
    for (const e of this.edits) {
      if (!byFile.has(e.path)) byFile.set(e.path, [])
      byFile.get(e.path)!.push(e)
    }
    for (const [path, edits] of byFile) {
      const first = edits[0]
      if (!first) continue
      lines.push(`- \`${path}\` — ${first.type === 'new' ? 'new file' : `${edits.length} edit${edits.length === 1 ? '' : 's'}`}`)
      for (const e of edits) lines.push(`  - ${e.reason}`)
    }
    return lines.join('\n')
  }

  editCount(): number {
    return this.edits.length
  }
}

// =====================================================================
// MAIN — propose a code change
// =====================================================================

export interface ProposeCodeChangeInput {
  repo: string
  instruction: string
}

export interface ProposeCodeChangeResult {
  ok: boolean
  repo?: RepoKey
  pr_number?: number
  pr_url?: string
  branch?: string
  diff_summary?: string
  files_changed?: string[]
  agent_summary?: string
  iterations?: number
  note?: string
  error?: string
}

export async function proposeCodeChange(input: ProposeCodeChangeInput): Promise<ProposeCodeChangeResult> {
  const { instruction } = input
  const repoKey = input.repo

  // Validate repo
  if (!isManagedRepo(repoKey)) {
    return { ok: false, error: `repo "${repoKey}" is not in the managed list. Allowed: ${Object.keys(MANAGED_REPOS).join(', ')}` }
  }
  if (!instruction || instruction.trim().length < 5) {
    return { ok: false, error: 'instruction is too short — describe what to change' }
  }

  // Anthropic client for the sub-loop
  const anthropicKey = process.env.NUXT_ANTHROPIC_API_KEY
  if (!anthropicKey) {
    return { ok: false, error: 'NUXT_ANTHROPIC_API_KEY not set' }
  }
  if (!process.env.NUXT_GITHUB_TOKEN) {
    return { ok: false, error: 'NUXT_GITHUB_TOKEN not set' }
  }

  const client = new Anthropic({ apiKey: anthropicKey })
  const stager = new EditStager()

  // Sub-loop messages
  const messages: Anthropic.MessageParam[] = [
    {
      role: 'user',
      content: `Repository: ${MANAGED_REPOS[repoKey].label} (${MANAGED_REPOS[repoKey].owner}/${MANAGED_REPOS[repoKey].repo})\nInstruction: ${instruction}`,
    },
  ]

  let iteration = 0
  let agentSummary = ''
  let stopReason: 'done' | 'max_iterations' | 'no_tool_call' | 'error' = 'no_tool_call'

  while (iteration < MAX_ITERATIONS) {
    iteration++

    let response: Anthropic.Message
    try {
      response = await client.messages.create({
        model: MODEL,
        max_tokens: 2048,
        temperature: 0.2,
        system: SUB_AGENT_SYSTEM_PROMPT,
        tools: SUB_AGENT_TOOLS,
        messages,
      })
    } catch (err) {
      return { ok: false, error: `sub-agent API error on iteration ${iteration}: ${err instanceof Error ? err.message : 'unknown'}` }
    }

    // Append assistant message to history
    messages.push({ role: 'assistant', content: response.content })

    // Find tool calls
    const toolUses = response.content.filter((b): b is Anthropic.ToolUseBlock => b.type === 'tool_use')
    if (toolUses.length === 0) {
      stopReason = 'no_tool_call'
      break
    }

    // Execute each tool call, collect tool_result blocks
    const toolResults: Anthropic.ToolResultBlockParam[] = []
    let saidDone = false

    for (const tu of toolUses) {
      const result = await executeSubAgentTool(repoKey, tu.name, tu.input as Record<string, unknown>, stager)
      toolResults.push({
        type: 'tool_result',
        tool_use_id: tu.id,
        content: typeof result.content === 'string' ? result.content : JSON.stringify(result.content),
        is_error: result.isError ?? false,
      })
      if (tu.name === 'done') {
        agentSummary = String((tu.input as { summary?: string }).summary ?? '').trim()
        saidDone = true
      }
    }

    messages.push({ role: 'user', content: toolResults })

    if (saidDone) {
      stopReason = 'done'
      break
    }
  }

  if (iteration >= MAX_ITERATIONS && stopReason !== 'done') {
    stopReason = 'max_iterations'
  }

  // Nothing staged? Nothing to commit.
  if (stager.editCount() === 0) {
    return {
      ok: false,
      repo: repoKey,
      iterations: iteration,
      agent_summary: agentSummary || `(no summary — stopped after ${stopReason})`,
      error: stopReason === 'done'
        ? 'sub-agent finished without staging any edits — check the summary for why'
        : `sub-agent stopped (${stopReason}) without staging edits`,
    }
  }

  // Commit + PR
  try {
    const branchName = makeBranchName(instruction)
    await createBranch(repoKey, branchName)
    await commitMultipleFiles(
      repoKey,
      branchName,
      stager.toChanges(),
      shortTitle(instruction),
    )
    const prBody = renderPrBody(instruction, agentSummary, stager.toPrBody())
    const pr = await createPullRequest(repoKey, branchName, shortTitle(instruction), prBody)

    return {
      ok: true,
      repo: repoKey,
      pr_number: pr.number,
      pr_url: pr.html_url,
      branch: branchName,
      diff_summary: stager.toPrBody(),
      files_changed: stager.editedFiles(),
      agent_summary: agentSummary,
      iterations: iteration,
      note: `PR open. Vercel preview URL usually appears within 30-90s — call get_pr_status({pr_number: ${pr.number}, repo: "${repoKey}"}) to fetch it.`,
    }
  } catch (err) {
    return {
      ok: false,
      repo: repoKey,
      error: `failed to commit/PR: ${err instanceof Error ? err.message : 'unknown'}`,
      diff_summary: stager.toPrBody(),
      agent_summary: agentSummary,
      iterations: iteration,
    }
  }
}

// =====================================================================
// SUB-AGENT TOOL DISPATCH
// =====================================================================

interface SubAgentToolResult {
  content: string | Record<string, unknown>
  isError?: boolean
}

async function executeSubAgentTool(
  repoKey: RepoKey,
  name: string,
  input: Record<string, unknown>,
  stager: EditStager,
): Promise<SubAgentToolResult> {
  try {
    switch (name) {
      case 'list_repo_directory': {
        const prefix = String(input.path_prefix ?? '')
        const tree = await listRepoTree(repoKey)
        const filtered = tree.filter(e => e.type === 'blob' && (!prefix || e.path.startsWith(prefix)))
        // Cap to avoid blowing the context window
        const capped = filtered.slice(0, 500)
        return {
          content: {
            count: filtered.length,
            shown: capped.length,
            paths: capped.map(e => e.path),
            note: filtered.length > capped.length ? `Showing first ${capped.length} of ${filtered.length}. Use a more specific path_prefix to narrow.` : undefined,
          },
        }
      }
      case 'read_repo_file': {
        const path = String(input.path ?? '')
        const guard = isForbiddenPath(path)
        if (!guard.allowed) return { content: `refused: ${guard.reason}`, isError: true }
        if (stager.readCount() >= MAX_FILES_READ) {
          return { content: `refused: already read ${MAX_FILES_READ} files (the cap). You have enough to stage your edits.`, isError: true }
        }
        const f = await readFile(repoKey, path)
        if (f.content.length > MAX_FILE_BYTES) {
          return { content: `refused: file is ${f.content.length} bytes — too large to load. Pick a smaller file.`, isError: true }
        }
        stager.recordRead(path, f.content)
        return { content: f.content }
      }
      case 'propose_edit': {
        const path = String(input.path ?? '')
        const guard = isForbiddenPath(path)
        if (!guard.allowed) return { content: `refused: ${guard.reason}`, isError: true }
        const oldStr = String(input.old_string ?? '')
        const newStr = String(input.new_string ?? '')
        const reason = String(input.reason ?? '')
        const result = stager.stageEdit(path, oldStr, newStr, reason)
        if (!result.ok) return { content: result.error ?? 'edit refused', isError: true }
        return { content: `edit staged on ${path} (${stager.editedFiles().length} of ${MAX_FILES_EDITED} files used so far)` }
      }
      case 'propose_new_file': {
        const path = String(input.path ?? '')
        const guard = isForbiddenPath(path)
        if (!guard.allowed) return { content: `refused: ${guard.reason}`, isError: true }
        const content = String(input.content ?? '')
        const reason = String(input.reason ?? '')
        const result = stager.stageNewFile(path, content, reason)
        if (!result.ok) return { content: result.error ?? 'new file refused', isError: true }
        return { content: `new file staged at ${path}` }
      }
      case 'done': {
        return { content: `done — ${stager.editCount()} edit(s) staged across ${stager.editedFiles().length} file(s)` }
      }
      default:
        return { content: `unknown tool: ${name}`, isError: true }
    }
  } catch (err) {
    return { content: `tool error: ${err instanceof Error ? err.message : 'unknown'}`, isError: true }
  }
}

// =====================================================================
// HELPERS — branch naming, PR body
// =====================================================================

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 40)
}

function makeBranchName(instruction: string): string {
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  return `mimir/${slug(instruction) || 'change'}-${ts}`
}

function shortTitle(instruction: string): string {
  const t = instruction.trim().split('\n')[0] ?? instruction.trim()
  return t.length > 72 ? t.slice(0, 69) + '...' : t
}

function renderPrBody(instruction: string, agentSummary: string, perFile: string): string {
  return [
    '## Instruction',
    instruction,
    '',
    '## What changed',
    agentSummary || '(no summary)',
    '',
    '## Files',
    perFile,
    '',
    '---',
    '_Opened by Mimir. Merging deploys to production via Vercel._',
  ].join('\n')
}

// =====================================================================
// CALLABLE FROM TOOLS.TS — read-side and merge-side
// =====================================================================

export interface PrStatus {
  ok: boolean
  repo: RepoKey
  pr_number: number
  pr_url: string
  state: 'open' | 'closed'
  merged: boolean
  title: string
  branch: string
  preview_url: string | null
  preview_note?: string
}

export async function getPrStatus(repoKey: string, prNumber: number): Promise<PrStatus | { ok: false; error: string }> {
  if (!isManagedRepo(repoKey)) return { ok: false, error: `repo "${repoKey}" not managed` }
  try {
    const pr = await getPullRequest(repoKey, prNumber)
    const previewUrl = pr.state === 'open' ? await getVercelPreviewUrl(repoKey, prNumber) : null
    return {
      ok: true,
      repo: repoKey,
      pr_number: pr.number,
      pr_url: pr.html_url,
      state: pr.state,
      merged: pr.merged,
      title: pr.title,
      branch: pr.head.ref,
      preview_url: previewUrl,
      preview_note: previewUrl
        ? undefined
        : pr.state === 'open'
          ? 'Vercel preview not yet posted. Wait 30-90s and re-check.'
          : 'PR is closed — no preview.',
    }
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) }
  }
}

export async function listOpenPrsForRepo(repoKey: string): Promise<{ ok: boolean; repo?: RepoKey; prs?: Array<Pick<PullRequest, 'number' | 'html_url' | 'title' | 'head'>>; error?: string }> {
  if (!isManagedRepo(repoKey)) return { ok: false, error: `repo "${repoKey}" not managed` }
  try {
    const prs = await listOpenPullRequests(repoKey)
    return {
      ok: true,
      repo: repoKey,
      prs: prs.map(p => ({ number: p.number, html_url: p.html_url, title: p.title, head: p.head })),
    }
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) }
  }
}

export async function mergePr(repoKey: string, prNumber: number): Promise<{ ok: boolean; merged: boolean; repo?: RepoKey; pr_url?: string; message?: string }> {
  if (!isManagedRepo(repoKey)) return { ok: false, merged: false, message: `repo "${repoKey}" not managed` }
  try {
    const pr = await getPullRequest(repoKey, prNumber)
    if (pr.state !== 'open') return { ok: false, merged: pr.merged, repo: repoKey, pr_url: pr.html_url, message: `PR is ${pr.state}` }
    const result = await mergePullRequest(repoKey, prNumber, { method: 'squash' })
    return { ok: result.merged, merged: result.merged, repo: repoKey, pr_url: pr.html_url, message: result.message }
  } catch (err) {
    return { ok: false, merged: false, repo: repoKey, message: err instanceof Error ? err.message : String(err) }
  }
}

export async function githubHealthCheck() {
  return whoAmI()
}

export { listManagedRepos } from './github-client'
