/**
 * Florida DBPR (Department of Business and Professional Regulation) license verifier.
 *
 * Strategy: prefer a local JSON snapshot (fast, free, offline) and fall back to
 * the public web search for anything not in the snapshot.
 *
 * The snapshot is generated by scripts/sync-dbpr.ts which downloads the official
 * licensee data from https://www2.myfloridalicense.com/dbpr/contractor-construction/
 * and filters to the 8 construction industry license classes Adam targets.
 *
 * Data sources & license-class mapping based on FL Construction Industry Licensing Board:
 *   CGC — Certified General Contractor
 *   CBC — Certified Building Contractor
 *   CRC — Certified Residential Contractor
 *   CCC — Certified Roofing Contractor
 *   CMC — Certified Mechanical Contractor (HVAC)
 *   CFC — Certified Plumbing Contractor
 *   CAC — Certified Class A Air Conditioning
 *   CPC — Certified Pool Contractor
 *   EC  — Certified Electrical Contractor
 *
 * Each entry from DBPR has: license number, license type, license status,
 * primary status, secondary status, issue date, expiration date, business name,
 * dba name, owner name, county, city, ZIP.
 */
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import type { FloridaLicense, LicenseClass, LicenseStatus } from './lead-db'

// =====================================================================
// SNAPSHOT (local JSON)
// =====================================================================

const SNAPSHOT_PATH = join(process.cwd(), 'server', 'data', 'dbpr-snapshot.json')

export interface DbprRecord {
  license_number: string          // e.g. "CGC1521234"
  license_class: LicenseClass     // e.g. "CGC"
  license_status: LicenseStatus
  business_name: string
  dba_name?: string
  owner_name?: string
  city: string
  county: string
  zip?: string
  issue_date?: string             // ISO
  expiration_date?: string        // ISO
  discipline_count?: number
}

interface SnapshotFile {
  generated_at: string
  source_url?: string
  count: number
  records: DbprRecord[]
}

let snapshotCache: SnapshotFile | null = null
let snapshotLoadedAt = 0
const SNAPSHOT_CACHE_TTL_MS = 60 * 60 * 1000  // re-read once an hour

function loadSnapshot(): SnapshotFile | null {
  if (snapshotCache && Date.now() - snapshotLoadedAt < SNAPSHOT_CACHE_TTL_MS) return snapshotCache
  if (!existsSync(SNAPSHOT_PATH)) {
    snapshotCache = null
    return null
  }
  try {
    snapshotCache = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf-8')) as SnapshotFile
    snapshotLoadedAt = Date.now()
    return snapshotCache
  } catch {
    return null
  }
}

// =====================================================================
// MAIN ENTRY
// =====================================================================

export interface VerifyInput {
  business_name?: string
  city?: string
  license_number?: string  // shortcut if Adam already has it
  domain?: string          // for reporting only
}

export interface VerifyResult {
  ok: boolean
  matched: boolean
  source: 'local_snapshot' | 'remote_search' | 'manual' | 'none'
  license?: FloridaLicense
  candidates?: DbprRecord[]   // when there are multiple matches, returned for human review
  note?: string
}

/**
 * Verify a contractor's FL license. Returns a normalized FloridaLicense suitable
 * for upserting into the lead DB.
 *
 * Match strategy:
 *   1. If license_number given, exact lookup in snapshot
 *   2. Else, snapshot search on business_name + (city if provided)
 *   3. Else, remote web search (limited — DBPR's form is stateful)
 *   4. Else, return matched=false with no_license_found
 */
export async function verifyFloridaLicense(input: VerifyInput): Promise<VerifyResult> {
  const snapshot = loadSnapshot()
  const businessName = (input.business_name ?? '').trim()
  const city = (input.city ?? '').trim()

  // Path 1: by license number
  if (input.license_number && snapshot) {
    const norm = input.license_number.toUpperCase().replace(/\s+/g, '')
    const record = snapshot.records.find(r => r.license_number.toUpperCase().replace(/\s+/g, '') === norm)
    if (record) {
      return {
        ok: true,
        matched: true,
        source: 'local_snapshot',
        license: toFloridaLicense(record, 'local_snapshot'),
      }
    }
  }

  // Path 2: by business name (+ city) in snapshot
  if (snapshot && businessName) {
    const matches = searchSnapshotByName(snapshot.records, businessName, city)
    if (matches.length === 1) {
      return {
        ok: true,
        matched: true,
        source: 'local_snapshot',
        license: toFloridaLicense(matches[0]!, 'local_snapshot'),
      }
    }
    if (matches.length > 1) {
      // Pick the best by status priority + tenure, but also return candidates
      const best = pickBestRecord(matches)
      return {
        ok: true,
        matched: true,
        source: 'local_snapshot',
        license: toFloridaLicense(best, 'local_snapshot'),
        candidates: matches.slice(0, 5),
        note: `${matches.length} matches found in snapshot — picked the active one with highest tenure`,
      }
    }
  }

  // Path 3: remote search (best-effort — DBPR's public form is fragile)
  if (businessName) {
    try {
      const remote = await searchDbprRemote(businessName, city)
      if (remote && remote.length === 1) {
        return {
          ok: true,
          matched: true,
          source: 'remote_search',
          license: toFloridaLicense(remote[0]!, 'remote_search'),
        }
      }
      if (remote && remote.length > 1) {
        const best = pickBestRecord(remote)
        return {
          ok: true,
          matched: true,
          source: 'remote_search',
          license: toFloridaLicense(best, 'remote_search'),
          candidates: remote.slice(0, 5),
          note: `${remote.length} matches via remote search — picked best`,
        }
      }
    } catch (err) {
      return {
        ok: false,
        matched: false,
        source: 'none',
        note: `remote search failed: ${err instanceof Error ? err.message : 'unknown'}. Run pnpm sync-dbpr or attach the license manually.`,
      }
    }
  }

  return {
    ok: true,
    matched: false,
    source: snapshot ? 'local_snapshot' : 'none',
    note: snapshot
      ? `no license matched "${businessName}"${city ? ` in ${city}` : ''}. Snapshot has ${snapshot.count} contractor records (generated ${snapshot.generated_at}). Could be unlicensed or in another state.`
      : 'no DBPR snapshot loaded — run `pnpm sync-dbpr` to populate it, or attach the license manually.',
  }
}

// =====================================================================
// SNAPSHOT SEARCH (local)
// =====================================================================

function searchSnapshotByName(records: DbprRecord[], businessName: string, city: string): DbprRecord[] {
  const needle = tokenize(businessName)
  if (needle.length === 0) return []
  const cityLower = city.toLowerCase()
  const scored: Array<{ r: DbprRecord; score: number }> = []
  for (const r of records) {
    const haystack = tokenize(`${r.business_name} ${r.dba_name ?? ''}`)
    const overlap = needle.filter(t => haystack.includes(t)).length
    if (overlap === 0) continue
    let score = overlap / needle.length
    // City boost — same city dominates
    if (cityLower && r.city.toLowerCase() === cityLower) score += 0.5
    // Status boost — active wins ties
    if (r.license_status === 'active') score += 0.1
    scored.push({ r, score })
  }
  scored.sort((a, b) => b.score - a.score)
  // Filter to those with ≥60% token overlap to reduce noise
  return scored.filter(s => s.score >= 0.6).map(s => s.r)
}

function tokenize(s: string): string[] {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(t => t.length >= 3 && !STOP_WORDS.has(t))
}

const STOP_WORDS = new Set(['inc', 'llc', 'co', 'corp', 'company', 'contracting', 'services', 'service', 'the', 'and', 'group'])

function pickBestRecord(records: DbprRecord[]): DbprRecord {
  const ranked = [...records].sort((a, b) => {
    const statusRank = (r: DbprRecord): number => r.license_status === 'active' ? 0 : r.license_status === 'expired' ? 1 : 2
    const aRank = statusRank(a)
    const bRank = statusRank(b)
    if (aRank !== bRank) return aRank - bRank
    // Tenure as tiebreaker — older license wins
    const aIssue = a.issue_date ? new Date(a.issue_date).getTime() : 0
    const bIssue = b.issue_date ? new Date(b.issue_date).getTime() : 0
    return aIssue - bIssue
  })
  return ranked[0]!
}

// =====================================================================
// REMOTE SEARCH (best-effort web scrape)
// =====================================================================

/**
 * DBPR public licensee search lives at https://www.myfloridalicense.com/wl11.asp
 * It's a stateful ASP form (cookies + ViewState). Fully scraping it from a
 * stateless Vercel function is fragile.
 *
 * For now we attempt a single-shot POST and parse the result; if it fails, the
 * caller falls back to "matched: false" with a note. This is intentional — the
 * snapshot path is the primary lookup; remote is bonus.
 *
 * If this proves brittle, swap for an Apify actor (e.g. someone's
 * "Florida DBPR Licensee Search" actor) — same interface.
 */
async function searchDbprRemote(businessName: string, city: string): Promise<DbprRecord[] | null> {
  // Stub: returns null so the caller falls back gracefully.
  // TODO: implement remote scrape OR swap for an Apify actor when one's available.
  // The point of this stub is to keep the interface ready so we can drop in
  // real remote lookup without changing the callers.
  return null
}

// =====================================================================
// NORMALIZATION → FloridaLicense
// =====================================================================

function toFloridaLicense(r: DbprRecord, source: 'local_snapshot' | 'remote_search'): FloridaLicense {
  const years_tenure = r.issue_date
    ? Math.max(0, Math.floor((Date.now() - new Date(r.issue_date).getTime()) / (365 * 24 * 3600 * 1000)))
    : undefined
  return {
    number: r.license_number,
    class: r.license_class,
    status: r.license_status,
    matched_business_name: r.business_name,
    matched_via: source,
    discipline_count: r.discipline_count ?? 0,
    ...(r.issue_date ? { issue_date: r.issue_date } : {}),
    ...(r.expiration_date ? { expiration_date: r.expiration_date } : {}),
    ...(years_tenure !== undefined ? { years_tenure } : {}),
    checked_at: new Date().toISOString(),
  }
}

// =====================================================================
// PUBLIC: snapshot status (used by Mimir to report freshness)
// =====================================================================

export function snapshotStatus(): { loaded: boolean; count: number; generated_at: string | null } {
  const snap = loadSnapshot()
  if (!snap) return { loaded: false, count: 0, generated_at: null }
  return { loaded: true, count: snap.count, generated_at: snap.generated_at }
}

// =====================================================================
// MANUAL ATTACH — Adam knows the license, just write it in
// =====================================================================

export interface ManualAttachInput {
  license_number: string
  status?: LicenseStatus
  issue_date?: string
  expiration_date?: string
  matched_business_name?: string
}

/**
 * Build a FloridaLicense from a known license number. Derives class from the
 * letter prefix (CGC, CBC, CRC, CCC, CMC, CFC, CAC, CPC, EC). Defaults to
 * "active" if Adam doesn't specify.
 */
export function buildManualLicense(input: ManualAttachInput): FloridaLicense {
  const raw = input.license_number.toUpperCase().replace(/\s+/g, '')
  const classPrefix = raw.replace(/[^A-Z]/g, '').slice(0, 3) || 'UNKNOWN'
  const issue_date = input.issue_date
  const years_tenure = issue_date
    ? Math.max(0, Math.floor((Date.now() - new Date(issue_date).getTime()) / (365 * 24 * 3600 * 1000)))
    : undefined
  return {
    number: raw,
    class: classPrefix,
    status: input.status ?? 'active',
    matched_via: 'manual',
    discipline_count: 0,
    ...(issue_date ? { issue_date } : {}),
    ...(input.expiration_date ? { expiration_date: input.expiration_date } : {}),
    ...(years_tenure !== undefined ? { years_tenure } : {}),
    ...(input.matched_business_name ? { matched_business_name: input.matched_business_name } : {}),
    checked_at: new Date().toISOString(),
  }
}

// Known FL DBPR construction license prefixes — used to validate prefixes the
// model produces and to give Mimir a hint about what's likely real vs. typo.
export const KNOWN_LICENSE_CLASSES = new Set([
  'CGC', 'CBC', 'CRC',  // general / building / residential
  'CCC',                // roofing
  'CMC', 'CAC',         // HVAC
  'CFC',                // plumbing
  'CPC',                // pool
  'EC',                 // electrical
])

export function isKnownLicenseClass(c: string): boolean {
  return KNOWN_LICENSE_CLASSES.has(c.toUpperCase())
}
