/**
 * Loads the bundled ops library snapshot and provides keyword search.
 * The snapshot is generated by scripts/sync-ops-context.ts.
 */
import opsSnapshot from '~/server/data/ops-context.json'

interface OpsFile {
  path: string
  title: string
  folder: string
  content: string
  excerpt: string
  tags: string[]
  bytes: number
}

interface OpsSnapshot {
  files: OpsFile[]
  syncedAt: string
  fileCount: number
  sourceDir?: string
  note?: string
}

const snapshot = opsSnapshot as OpsSnapshot

export function opsSyncStatus(): { fileCount: number; syncedAt: string; isEmpty: boolean } {
  return {
    fileCount: snapshot.files.length,
    syncedAt: snapshot.syncedAt,
    isEmpty: snapshot.files.length === 0,
  }
}

/**
 * Returns the top N files matching the query. Naive word-overlap scoring —
 * good enough for ~50 well-organized markdown files.
 */
export function searchOpsLibrary(query: string, limit = 4): Array<{
  path: string
  title: string
  folder: string
  excerpt: string
  score: number
  snippet: string
}> {
  if (snapshot.files.length === 0) return []

  const q = query.toLowerCase().trim()
  if (!q) return []

  const terms = q.split(/[\s,.\-_/]+/).filter(t => t.length > 2)
  if (terms.length === 0) return []

  const scored = snapshot.files.map(file => {
    const haystack = `${file.path} ${file.title} ${file.folder} ${file.content} ${file.tags.join(' ')}`.toLowerCase()
    let score = 0
    // Path/title matches weighted higher
    const pathTitle = `${file.path} ${file.title} ${file.folder}`.toLowerCase()
    for (const term of terms) {
      // Word boundary match in title/path = +5
      const titleRe = new RegExp(`\\b${escapeRegex(term)}\\b`, 'g')
      const titleMatches = (pathTitle.match(titleRe) || []).length
      score += titleMatches * 5

      // Substring match in content = +1
      const contentMatches = (haystack.match(new RegExp(escapeRegex(term), 'g')) || []).length
      score += contentMatches
    }

    // Make a snippet — the first instance of any term in context
    let snippet = file.excerpt
    for (const term of terms) {
      const idx = file.content.toLowerCase().indexOf(term)
      if (idx >= 0) {
        const start = Math.max(0, idx - 80)
        const end = Math.min(file.content.length, idx + 240)
        snippet = (start > 0 ? '...' : '') + file.content.slice(start, end).replace(/\n+/g, ' ').trim() + (end < file.content.length ? '...' : '')
        break
      }
    }

    return { file, score, snippet }
  })

  scored.sort((a, b) => b.score - a.score)
  return scored
    .filter(s => s.score > 0)
    .slice(0, limit)
    .map(s => ({
      path: s.file.path,
      title: s.file.title,
      folder: s.file.folder,
      excerpt: s.file.excerpt,
      score: s.score,
      snippet: s.snippet,
    }))
}

/**
 * Returns the full content of a specific file by exact path match.
 */
export function getOpsFile(path: string): OpsFile | null {
  return snapshot.files.find(f => f.path === path) ?? null
}

/**
 * Returns a folder-level summary — useful for "what's in 02-Agents?" type queries.
 */
export function listOpsFolder(folder: string): Array<{ path: string; title: string; excerpt: string }> {
  return snapshot.files
    .filter(f => f.folder === folder || f.path.startsWith(`${folder}/`))
    .map(f => ({ path: f.path, title: f.title, excerpt: f.excerpt }))
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
